spring:
  application:
    name: spring-pekko-synchronization
  actor-enabled: true
  actor:
    pekko:
      name: spring-pekko-example
      actor:
        provider: cluster
        allow-java-serialization: on
        warn-about-java-serializer-usage: off
      remote:
        artery:
          canonical:
            hostname: 127.0.0.1
            port: 2551
      cluster:
        name: spring-pekko-example
        seed-nodes:
          - pekko://spring-pekko-example@127.0.0.1:2551
          - pekko://spring-pekko-example@127.0.0.1:2552
          - pekko://spring-pekko-example@127.0.0.1:2553
        downing-provider-class: org.apache.pekko.cluster.sbr.SplitBrainResolverProvider

  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/counter_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379

  # Initialize schema
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8080

logging:
  level:
    org.apache.pekko: INFO
    io.github.seonwkim.example: DEBUG
    org.springframework.data: INFO
