spring:
  application:
    name: spring-pekko
  actor:
    pekko:
      name: spring-pekko-example
      actor:
        provider: cluster
        allow-java-serialization: off
        warn-about-java-serializer-usage: on
      remote:
        artery:
          canonical:
            hostname: ${PEKKO_HOSTNAME:127.0.0.1}
            port: ${PEKKO_PORT:2551}
      cluster:
        name: spring-pekko-example
        seed-nodes: ${SEED_NODES:pekko://spring-pekko-example@127.0.0.1:2551,pekko://spring-pekko-example@127.0.0.1:2552,pekko://spring-pekko-example@127.0.0.1:2553}
        downing-provider-class: org.apache.pekko.cluster.sbr.SplitBrainResolverProvider

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.apache.pekko: DEBUG

management:
  metrics:
    tags:
      application: spring-pekko-example
  endpoints:
    web:
      exposure:
        include: prometheus, actor-cluster-state
