name: Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: gradle

      - name: 🧪 Check required secrets
        run: |
          echo "🔐 Checking required secrets..."
          [[ -n "$ORG_GRADLE_PROJECT_mavenCentralUsername" ]] || { echo "❌ MAVEN_CENTRAL_USERNAME not set"; exit 1; }
          [[ -n "$ORG_GRADLE_PROJECT_mavenCentralPassword" ]] || { echo "❌ MAVEN_CENTRAL_PASSWORD not set"; exit 1; }
          [[ -n "$ORG_GRADLE_PROJECT_signingInMemoryKey" ]] || { echo "❌ SIGNING_SECRET_KEY not set"; exit 1; }
          [[ -n "$ORG_GRADLE_PROJECT_signingInMemoryKeyPassword" ]] || { echo "❌ SIGNING_PASSWORD not set"; exit 1; }
          echo "✅ All required secrets are present."

        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      - name: 🚀 Publish to Maven Central (in-memory GPG)
        run: |
          echo "📦 Running ./gradlew publish..."
          ./gradlew :core:publishAndReleaseToMavenCentra --no-configuration-cache
          echo "✅ Publish completed successfully."

        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
